### ISSUE TITLE
0.1.0-SNAPSHOT on clojars depends on bitcoinj 0.7-SNAPSHOT

### ISSUE THREAD

**Issue by pgr0ss** [pelle/bitcljoin#1]
Your instructions build 0.7 of bitcoinj, but the pushed bitcljoin 0.1.0-SNAPSHOT depends on 0.7-SNAPSHOT. It seems like you need to push a new version of bitcljoin to clojars.

**Comment by pelle** [comment]
I've pushed a new version. It uses 0.7.3 of bitcoinj. See the readme for the hash.
